```{r global, cache = FALSE, include = FALSE, echo = FALSE}
    rm(list = ls())
    options(stringsAsFactors = FALSE)
    dir.create("Routput")
    library(knitr)
    
    knitr::write_bib(x = c("survival", "nlme", "JM"), file = "bib/Rpackages.bib")

### Word Hack to label equations
    is_docx_output <- function (fmt = knitr:::pandoc_to()) {
        if (length(fmt) == 0) {
            return(FALSE)
        } else {
            return(fmt == "docx")

        }
    }

    numberEq.docx <- function (eq, lab, envir = docx.eqcounter) {
        is_docx_output <- function (fmt = knitr:::pandoc_to()) {
            if (length(fmt) == 0) {
                return(FALSE)
            } else {
                return(fmt == "docx")
            }
        }
        if (is_docx_output() | knitr:::is_html_output()) {
            assign(x = "counter", value = get(x = "counter", envir = envir)+1, envir = envir)
            assign(x = gsub("eq:", "", lab), value = get(x = "counter", envir = envir), envir = envir)
            lab <- get("counter", envir = envir)
            neach <- 8
            return(paste0('$$', eq, paste0(rep('\\;', neach), collapse = ''), '(', lab, ')', '$$'))
        } else {
            out <- paste0('\\begin{equation}', eq, '(\\#', lab, ')\\end{equation}')
            if (knitr:::is_latex_output()) {
                return(out)
            } else {
                return(paste0("$$", out, "$$"))
            }
        }
    }

    labEq.docx <- function (lab, envir = docx.eqcounter) {
        is_docx_output <- function (fmt = knitr:::pandoc_to()) {
            if (length(fmt) == 0) {
                return(FALSE)
            } else {
                return(fmt == "docx")
            }
        }
        if (is_docx_output() | knitr:::is_html_output()) {
            paste0('(', get(x = gsub("eq:", "", lab), envir = envir), ')')
        } else {
            paste0('\\@ref(eq:', lab, ')')
        }
    }

    if (is_docx_output() | knitr:::is_html_output()) {
        docx.eqcounter <- new.env()
        docx.eqcounter$counter <- 0
        opts_knit$set(
            root.dir = normalizePath("Routput"),
            echo = FALSE,
            warning = FALSE,
            message = FALSE,
            cache = FALSE,
            include = FALSE
        )
        opts_chunk$set(
            root.dir = normalizePath("Routput"),
            echo = FALSE,
            warning = FALSE,
            message = FALSE,
            cache = FALSE,
            include = FALSE
        )
    } else {
        opts_knit$set(
            root.dir = normalizePath("Routput"),
            # fig.align = 'center',
            echo = FALSE,
            warning = FALSE,
            message = FALSE,
            cache = FALSE,
            include = FALSE,
            fig.pos = '!htb'
        )
        opts_chunk$set(
            root.dir = normalizePath("Routput"),
            # fig.align = 'center',
            echo = FALSE,
            warning = FALSE,
            message = FALSE,
            cache = FALSE,
            include = FALSE,
            fig.pos = '!htb'
        )
    }


    myPalette <- c("dodgerblue", "firebrick2", "springgreen3", "maroon2", "goldenrod2", "deepskyblue", "mediumpurple1", "tan1")


### Define nCores
    nCores <- min(parallel::detectCores(), ifelse(Sys.info()["nodename"]=="stat1", 100, 48))


### Load packages
    library(parallel)
    library(ggplot2)
    library(grid)
    library(scales)
    # library(xlsx)
    library(tidyr)
    library(broom)
    library(cowplot)

    library(ggrepel)

    library(myScriptsMickael)
    library(ggFunctions)

    library(JM)
    library(dplyr)
    library(relaimpo)
    library(data.table)
    # library(ReporteRs)
    library(viridis)
    scale_colour_viridis <- scale_color_viridis
    
    library(igraph)
    library(ggraph)
    library(pander)
    library(proftools)
```

```{r loadData}
    if (FALSE) {
        source("/disks/PROJECT/DESIR_longitudinal/Scripts/ArticleR/01-JointModelSimulations.R")
        # file.copy(from = "/disks/DATA/DESIR_longitudinal/ArticleR/DataArticle_20180102.Rdata", to = "/disks/PROJECT/DESIR_longitudinal/Scripts/ArticleRmd/Routput/DataArticle_20180102.Rdata", overwrite = TRUE)
        file.copy(from = "/disks/DATA/DESIR_longitudinal/ArticleR/DataArticle_20180102.Rdata", to = "/disks/PROJECT/Mickael/COMMUNICATION/ArticleRmd/Routput/DataArticle_20180102.Rdata", overwrite = TRUE)
    } else {
        # load(normalizePath("Routput/DataArticle.Rdata"))
        # load("./DataArticle_20180102.Rdata")
        load("/disks/PROJECT/DESIR_longitudinal/Scripts/ArticleRmd/Routput/DataArticle_20180102.Rdata")
    }
```
