## Model formulations

### Joint likelihood model (JM)

The standard formulation of the joint model involves two components: a longitudinal component and a time-to-event component.
Let $n$ denote the sample size, and $Y_{ij}$ the longitudinal measurements collected for each individual $i$ at time points $t_{ij}$, $i=1,\cdots,n$, $j=1,\cdots,m_i$, where $m_i$ is the number of measurements on individual $i$. 
The longitudinal component (i.e. measurements) typically consists of a (generalised) linear mixed effect (LME) model, whose within-subject correlation matrix is modelled using random-effect parameter vector $b_i=\begin{pmatrix}\theta_{0i}\\\theta_{1i}\end{pmatrix}$.

Under the joint likelihood framework implemented in "JM" [@rizopoulos_jm:_2010; @R-JM], within the class of "shared parameter models" [@elashoff_joint_2016; @rizopoulos_joint_2012], we define
`r numberEq.docx("Y_{ij}=X_{ij}+\\epsilon_{ij}", "eq:LongiSimple")`
where $Y_{ij}$ is the observed value and $X_{ij}$ is the true (unobserved) value of the longitudinal measurement at time $t_{ij}$ for individual $i$. 
The quantity $\epsilon_{ij}$ is a random error term usually assumed to be normally distributed:
`r numberEq.docx("\\epsilon_{ij}\\sim \\mathcal{N}(0,\\sigma^2)", "eq:LongiError")`

The quantity $X_{ij}$ is typically called the trajectory function, and is usually specified as a linear or quadratic function of time $t_{ij}$; for simplicity here, we assume linearity over time.
We also define $Z_i$, a vector denoting the genotype of individual $i$, and $W_i$, a set of adjusting covariates:
`r numberEq.docx("Y_{ij}=X_{ij}+\\epsilon_{ij}=\\theta_{0i}+\\theta_{1i}t_{ij}+\\gamma Z_i+\\delta W_i+\\epsilon_{ij}", "eq:LongiFull")`

Again, without any loss of generality, we omit the term $\delta W_i$ in the following. 
Random effects $\theta_{0i}$ (intercept) and $\theta_{1i}$ (slope) are assumed bivariate Normal: $\mathbf{\theta} \sim \mathcal{N}_2 (\mathbf{\mu},\mathbf{\Sigma})$, and independently distributed from $\epsilon_{ij}$. 
The coefficient $\gamma$ assesses the genotypic (additive) effect of variable $Z_i$ on the trajectory function. 
To account for varying slopes, an interaction term between $Z_i$ and time $t_{ij}$ could be added into the trajectory function; for simplicity, this term was not considered in this study.

The time-to-event (survival) component usually consists of a parametric (e.g. exponential or Weibull distribution) or semi-parametric (e.g. Cox proportional hazards) model. 
$T_i$ denotes the event time for individual $i$, and $C_i$ the right censoring time (end of the follow-up). 
Let $\Delta_i$ be the event indicator: $\Delta_i=0$, if $T_i>C_i$, and $\Delta_i=1$, if $T_i <= C_i$.
Under the Cox proportional hazards model, variable $T_i$ is specified using the following equation:
`r numberEq.docx("\\lambda_i(t)=\\lambda_0(t) \\exp(\\beta X_i(t)+\\alpha Z_i)", "eq:SurvFull")`

where $\lambda_i(t)$ is the hazard function at time $t$ for individual $i$ and $\lambda_0(t)$ is the unspecified baseline hazard function, which we assume piecewise constant with two knots placed at intermediate time points in the follow-up. 
Coefficient $\alpha$ measures the effect of $Z_i$ on the hazard function, while $\beta$ measures the association between the trajectory function and the hazard function.
In this formulation, we suppose that the subject-specific random effect parameters $b_i=\begin{pmatrix}\theta_{0i}\\\theta_{1i}\end{pmatrix}$ included in the trajectory $X_i(t)$ could modify the hazard function, which implies that $\beta$ is the parameter linking the longitudinal and survival components.

### Two-Step model (TS)

As an alternative to JM, and based on the work of @tsiatis_modeling_1995, the two-step model estimates parameters of the joint model by first, estimating parameters of the trajectory function $X_i(t)$ in Equation `r labEq.docx("eq:LongiFull")`, and second, by substituting this estimated trajectory, say $X^*_i(t)$, into `r labEq.docx("eq:SurvFull")` before fitting the Cox survival model.
