## Comparison of estimation accuracy

<!-- We explored the influence of several factors on the estimator accuracy when using a linear mixed effect model (LME) to estimate $\gamma$, and when using a Cox regression model with time-varying covariate (CoxPH) to estimate $\beta$ and $\alpha$, and compared it with the accuracy as obtained under the joint modelling approach (JM) and its Two-Step approximation (TS). -->
<!-- For each simulated scenario, we measured the root-mean-square error (RMSE) for the three parameters of interest ($\gamma$, $\beta$ and $\alpha$). -->
Due to the complexity of the estimating algorithm within JM, convergence could not be obtained ($`r signif(mean(1-checkFailure[, "Success"]/nKeep)*100, digits = 3)`\pm `r signif(sd(1-checkFailure[, "Success"]/nKeep)*100, digits = 3)`$% of convergence issues on average per scenario) for the whole set of `r nKeep` simulations (i.e. algorithm “piecewise-PH-aGH” for a time-dependent relative risk model with a piecewise constant baseline risk function, using the adaptive Gauss-Hermite quadrature rule to approximate integrals within the Expectation-Maximisation (EM) step [@rizopoulos_jm:_2010; @R-JM]). 

RMSE for parameter $\gamma$ (Figure \@ref(fig:RMSEgamma)) showed similar performance for JM and TS, which was expected given the formulation of the joint model within the "Shared Parameter Models" framework, in which $Y_i$ (mean of $Y_{ij}$ modelled within LME according to Equation `r labEq.docx("eq:LongiFull")`) links the longitudinal data to the time of event.
RMSE for parameter $\beta$ (Figure \@ref(fig:RMSEbeta)) and for parameter $\alpha$ (Figure \@ref(fig:RMSEalphaZoom)) were smaller within the joint modelling framework (either JM or TS) than in the more classical CoxPH model with time-varying fasting plasma glucose. 
While the RMSE for $\beta$ remains the same in the CoxPH model across all scenarios, under JM or TS it decreased whenever the sample size, the incidence rate or the allele frequency increases. 
Differences in RMSE for parameter $\alpha$ were smaller than for parameter $\beta$.
Both TS and CoxPH with time-dependent covariate performed similarly, probably because partial likelihood inferences were used in these two approaches. 
JM estimations were less biased in almost all scenarios when the sample size was greater than 2,500.

Overall, our simulations showed that JM is less biased than when separate approaches are used to model the effect of $Z_i$ on the longitudinal process $Y_i$, and on the time-to-event $T_i$.
While separate approaches performed well for parameters $\gamma$ and $\alpha$, the bias forparamter $\beta$ was the highest across all scenarios.  

For the default simulation settings (Table \@ref(tab:SimulationSettings)), Type 1 error and statistical power displayed similar results for both JM and TS (Table \@ref(tab:PowerType1TCF7L2)). 
Nevertheless, our simulations highlighted convergence issues occurring under the joint likelihood approach (19.4% of the power simulation study).

